-- MySQL Script generated by MySQL Workbench
-- Sat Oct  7 10:44:43 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema coordpis-bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coordpis-bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coordpis-bd` DEFAULT CHARACTER SET latin1 ;
USE `coordpis-bd` ;

-- -----------------------------------------------------
-- Table `coordpis-bd`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`cargo` (
  `CARID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CARNOMBRE` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`CARID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`departamento` (
  `id_departamento` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`grupo` (
  `GRUID` VARCHAR(20) NOT NULL,
  `GRUDESCRIPCION` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`GRUID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`materia` (
  `id_materia` INT(11) NOT NULL AUTO_INCREMENT,
  `semestre` VARCHAR(4) NULL DEFAULT NULL,
  `codigo_materia` VARCHAR(30) NULL DEFAULT NULL,
  `nombre_materia` VARCHAR(70) NOT NULL,
  `creditos` INT(11) NULL DEFAULT NULL,
  `intensidad_horaria` INT(11) NULL DEFAULT NULL,
  `numero_estudiantes` INT(11) NULL DEFAULT NULL,
  `grupos_solicitados` INT(11) NULL DEFAULT NULL,
  `grupos_cancelados` INT(11) NULL DEFAULT NULL,
  `grupos_ofertados` INT(11) NULL DEFAULT NULL,
  `grupos_fusionados` INT(11) NULL DEFAULT NULL,
  `grupos_nuevos` INT(11) NULL DEFAULT NULL,
  `id_departamento` INT(11) NOT NULL,
  PRIMARY KEY (`id_materia`),
  INDEX `fk_curso_departamento_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_curso_departamento`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `coordpis-bd`.`departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 83
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`usuario` (
  `USUID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CARID` BIGINT(20) NULL DEFAULT NULL,
  `USUFECHANACIMIENTO` DATETIME NOT NULL,
  `USUNOMBRES` VARCHAR(75) NOT NULL,
  `USUAPELLIDOS` VARCHAR(75) NOT NULL,
  `USUGENERO` CHAR(1) NOT NULL,
  `USUNOMBREUSUARIO` VARCHAR(75) NOT NULL,
  `USUCONTRASENA` VARCHAR(250) NOT NULL,
  `USUEMAIL` VARCHAR(150) NOT NULL,
  `USUFOTO` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`USUID`),
  INDEX `FK_USUARIOCARGO` (`CARID` ASC),
  CONSTRAINT `FK_USUARIOCARGO`
    FOREIGN KEY (`CARID`)
    REFERENCES `coordpis-bd`.`cargo` (`CARID`))
ENGINE = InnoDB
AUTO_INCREMENT = 65
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`usuariogrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`usuariogrupo` (
  `GRUID` VARCHAR(20) NOT NULL,
  `USUID` BIGINT(20) NOT NULL,
  `USUNOMBREUSUARIO` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`GRUID`, `USUID`),
  INDEX `FK_USUARIO_USUID` (`USUID` ASC),
  INDEX `FK_GRUPOS_GRUID` (`GRUID` ASC),
  CONSTRAINT `FK_GRUPOS_GRUID`
    FOREIGN KEY (`GRUID`)
    REFERENCES `coordpis-bd`.`grupo` (`GRUID`),
  CONSTRAINT `FK_USUARIO_USUID`
    FOREIGN KEY (`USUID`)
    REFERENCES `coordpis-bd`.`usuario` (`USUID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`facultad` (
  `idfacultad` INT NOT NULL AUTO_INCREMENT,
  `facultadNombre` VARCHAR(200) NULL,
  PRIMARY KEY (`idfacultad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`programa` (
  `idPrograma` INT NOT NULL AUTO_INCREMENT,
  `nombrePrograma` VARCHAR(200) NULL,
  `idfacultad` INT NOT NULL,
  PRIMARY KEY (`idPrograma`),
  INDEX `fk_programa_facultad1_idx` (`idfacultad` ASC),
  CONSTRAINT `fk_programa_facultad1`
    FOREIGN KEY (`idfacultad`)
    REFERENCES `coordpis-bd`.`facultad` (`idfacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`usuario_programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`usuario_programa` (
  `idUsuario` BIGINT(20) NOT NULL,
  `idPrograma` INT NOT NULL,
  INDEX `fk_usuario_programa_usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_usuario_programa_programa1_idx` (`idPrograma` ASC),
  PRIMARY KEY (`idUsuario`, `idPrograma`),
  CONSTRAINT `fk_usuario_programa_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `coordpis-bd`.`usuario` (`USUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_programa_programa1`
    FOREIGN KEY (`idPrograma`)
    REFERENCES `coordpis-bd`.`programa` (`idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`usuario_departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`usuario_departamento` (
  `idUsuario` BIGINT(20) NOT NULL,
  `idDepartamento` INT(11) NOT NULL,
  INDEX `fk_usuario_departamento_usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_usuario_departamento_departamento1_idx` (`idDepartamento` ASC),
  PRIMARY KEY (`idUsuario`, `idDepartamento`),
  CONSTRAINT `fk_usuario_departamento_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `coordpis-bd`.`usuario` (`USUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_departamento_departamento1`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `coordpis-bd`.`departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
