-- MySQL Script generated by MySQL Workbench
-- Wed Nov  8 13:07:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema coordpis-bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coordpis-bd
-- -----------------------------------------------------
USE `coordpis-bd` ;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`profesor` (
  `idProfesor` INT NOT NULL,
  `nombreProfesor` VARCHAR(50) NOT NULL,
  `programaProfesor` INT NOT NULL,
  `universidadProfesor` VARCHAR(50) NULL,
  `externoProfesor` BIT NULL,
  PRIMARY KEY (`idProfesor`),
  INDEX `fk_profesor_programa1_idx` (`programaProfesor` ASC),
  CONSTRAINT `fk_profesor_programa1`
    FOREIGN KEY (`programaProfesor`)
    REFERENCES `coordpis-bd`.`programa` (`idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`anteproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`anteproyecto` (
  `idAnteproyecto` INT NOT NULL,
  `tituloAnteproyecto` VARCHAR(100) NOT NULL,
  `fechaAnteproyecto` DATE NOT NULL,
  `programaAnteproyecto` INT NOT NULL,
  `directorAnteproyecto` INT NOT NULL,
  PRIMARY KEY (`idAnteproyecto`),
  INDEX `fk_anteproyecto_programa1_idx` (`programaAnteproyecto` ASC),
  INDEX `fk_anteproyecto_profesor1_idx` (`directorAnteproyecto` ASC),
  CONSTRAINT `fk_anteproyecto_programa1`
    FOREIGN KEY (`programaAnteproyecto`)
    REFERENCES `coordpis-bd`.`programa` (`idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anteproyecto_profesor1`
    FOREIGN KEY (`directorAnteproyecto`)
    REFERENCES `coordpis-bd`.`profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`estudiante` (
  `idEstudiante` INT NOT NULL,
  `codigoEstudiante` INT NOT NULL,
  `nombreEstudiante` VARCHAR(50) NOT NULL,
  `programaEstudiante` INT NOT NULL,
  PRIMARY KEY (`idEstudiante`),
  INDEX `fk_estudiante_programa1_idx` (`programaEstudiante` ASC),
  CONSTRAINT `fk_estudiante_programa1`
    FOREIGN KEY (`programaEstudiante`)
    REFERENCES `coordpis-bd`.`programa` (`idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`estudiante-anteproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`estudiante-anteproyecto` (
  `estudiante` INT NOT NULL,
  `anteproyecto` INT NOT NULL,
  INDEX `fk_estudiante-anteproyecto_estudiante1_idx` (`estudiante` ASC),
  INDEX `fk_estudiante-anteproyecto_anteproyecto1_idx` (`anteproyecto` ASC),
  PRIMARY KEY (`estudiante`, `anteproyecto`),
  CONSTRAINT `fk_estudiante-anteproyecto_estudiante1`
    FOREIGN KEY (`estudiante`)
    REFERENCES `coordpis-bd`.`estudiante` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante-anteproyecto_anteproyecto1`
    FOREIGN KEY (`anteproyecto`)
    REFERENCES `coordpis-bd`.`anteproyecto` (`idAnteproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`codirector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`codirector` (
  `profesor` INT NOT NULL,
  `anteproyecto` INT NOT NULL,
  INDEX `fk_coodirectores_profesor1_idx` (`profesor` ASC),
  INDEX `fk_coodirectores_anteproyecto1_idx` (`anteproyecto` ASC),
  PRIMARY KEY (`profesor`, `anteproyecto`),
  CONSTRAINT `fk_coodirectores_profesor1`
    FOREIGN KEY (`profesor`)
    REFERENCES `coordpis-bd`.`profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coodirectores_anteproyecto1`
    FOREIGN KEY (`anteproyecto`)
    REFERENCES `coordpis-bd`.`anteproyecto` (`idAnteproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`formatoA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`formatoA` (
  `idFormatoA` INT NOT NULL,
  `claveFormatoA` VARCHAR(45) NOT NULL,
  `anteproyectoFormatoA` INT NOT NULL,
  PRIMARY KEY (`idFormatoA`),
  INDEX `fk_formatoA_anteproyecto1_idx` (`anteproyectoFormatoA` ASC),
  CONSTRAINT `fk_formatoA_anteproyecto1`
    FOREIGN KEY (`anteproyectoFormatoA`)
    REFERENCES `coordpis-bd`.`anteproyecto` (`idAnteproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`formatoB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`formatoB` (
  `idFormatoB` INT NOT NULL,
  `claveFormatoB` VARCHAR(45) NULL,
  `anteproyectoFormatoB` INT NOT NULL,
  PRIMARY KEY (`idFormatoB`),
  INDEX `fk_formatoB_anteproyecto1_idx` (`anteproyectoFormatoB` ASC),
  CONSTRAINT `fk_formatoB_anteproyecto1`
    FOREIGN KEY (`anteproyectoFormatoB`)
    REFERENCES `coordpis-bd`.`anteproyecto` (`idAnteproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coordpis-bd`.`formatoC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordpis-bd`.`formatoC` (
  `idFormatoC` INT NOT NULL,
  `claveFormatoC` VARCHAR(45) NULL,
  `anteproyectoFormatoC` INT NOT NULL,
  PRIMARY KEY (`idFormatoC`),
  INDEX `fk_formatoC_anteproyecto1_idx` (`anteproyectoFormatoC` ASC),
  CONSTRAINT `fk_formatoC_anteproyecto1`
    FOREIGN KEY (`anteproyectoFormatoC`)
    REFERENCES `coordpis-bd`.`anteproyecto` (`idAnteproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
